<a href="https://colab.research.google.com/github/yashugupta786/Keras_layers_detail/blob/master/keras_embeddings_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words


Using TensorFlow backend.


[[26, 48], [40, 33], [19, 2], [49, 33], [18], [49], [41, 2], [3, 40], [41, 33], [22, 8, 48, 12]]


In [2]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[26 48  0  0]
 [40 33  0  0]
 [19  2  0  0]
 [49 33  0  0]
 [18  0  0  0]
 [49  0  0  0]
 [41  2  0  0]
 [ 3 40  0  0]
 [41 33  0  0]
 [22  8 48 12]]


In [3]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.compile('rmsprop','mse')
embeddings=model.predict(padded_docs)
print(embeddings)











[[[ 0.02815868  0.01946953 -0.03005728 -0.00321419 -0.04303196
   -0.00126998  0.03091338  0.0480368 ]
  [ 0.03209497  0.01001441 -0.00409777  0.04796961  0.0016076
   -0.01766706 -0.02172011 -0.04172415]
  [-0.01820119  0.0022464  -0.00431123 -0.0262556   0.02239097
   -0.02388175 -0.00440181 -0.04347557]
  [-0.01820119  0.0022464  -0.00431123 -0.0262556   0.02239097
   -0.02388175 -0.00440181 -0.04347557]]

 [[ 0.00522076 -0.04386137 -0.00909629 -0.03829919 -0.04086357
   -0.04323533  0.0465597   0.0052688 ]
  [ 0.00608804 -0.00265255 -0.01835129 -0.03175711  0.01810208
    0.03913397 -0.01319851 -0.00221466]
  [-0.01820119  0.0022464  -0.00431123 -0.0262556   0.02239097
   -0.02388175 -0.00440181 -0.04347557]
  [-0.01820119  0.0022464  -0.00431123 -0.0262556   0.02239097
   -0.02388175 -0.00440181 -0.04347557]]

 [[-0.00183544 -0.0145914   0.02379962  0.04096531 -0.0168692
   -0.02165581  0.01494062  0.04186423]
  [-0.02400312  0.00594757 -0.01487224  0.04987403 -0.0129340